# Generated by Django 5.2.5 on 2025-08-16 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profiles', to='registration.register')),
            ],
        ),
        migrations.CreateModel(
            name='CaretakerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_timings', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_patients', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='caretaker_id_proofs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_profiles', to='registration.register')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='registration.register')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('license_number', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profiles', to='registration.register')),
            ],
        ),
    ]
