# Generated by Django 5.2.5 on 2025-08-30 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_adminprofile_caretakerprofile_customerprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaretakerBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in hours')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='registration.caretakerprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='registration.customerprofile')),
            ],
        ),
    ]
